# Generated by Django 3.2.14 on 2022-07-25 18:11

from django.db import migrations
from apps.blog.models import Tag


def add_blog_tags(apps, schema_editor):
    tags = [
        'Открытие',
        'Новости',
        'Скидки',
        'Коллаборации',
        'Обновление ассортимента',
    ]
    for tag in tags:
        Tag.objects.create(name=tag)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_tag_article_tags'),
    ]

    operations = [
        migrations.RunPython(add_blog_tags)
    ]
