# Generated by Django 3.2.14 on 2022-07-25 19:09

from django.db import migrations
from apps.blog.models import Article, Tag


def add_tags_connections(apps, schema_editor):
    tags = [
        Tag.objects.get(name='Открытие'),
        Tag.objects.get(name='Новости')
    ]
    articles = Article.objects.all()
    for article in articles:
        for tag in tags:
            article.tags.add(tag)
    Article.objects.get(title='Мы открылись').tags.add((Tag.objects.get(name='Скидки')))


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_add_blog_tags'),
    ]

    operations = [
        migrations.RunPython(add_tags_connections)
    ]
