# Generated by Django 4.0.6 on 2022-08-01 14:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='blog/article/', verbose_name='Изображение'),
        ),
    ]
