# Generated by Django 4.0.6 on 2022-10-03 14:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220823_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
